In [2]:
my_list = {1,2,3,4}

In [3]:
print(my_list)

{1, 2, 3, 4}


In [7]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [8]:
print(arr.ndim)

1


In [10]:
print(arr.shape)

(4,)


In [11]:
print(arr.dtype)

int64


In [14]:
arr + 5

array([6, 7, 8, 9])

In [15]:
arr * 2

array([2, 4, 6, 8])

In [18]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
print(a+b)

[11 22 33 44]


In [20]:
arr = np.array([10,20,30,40])
print(arr[0])
print(arr[-1])
print(arr[1:3])

10
40
[20 30]


In [21]:
matrix = np.array([
    [1,2,3,4],
    [4,5,6,7]
])
print(matrix)

[[1 2 3 4]
 [4 5 6 7]]


In [22]:
print(matrix[0,1])

2


In [23]:
arr = np.array([1,2,3,4,5,6])
print(arr.sum())

21


In [24]:
print(arr.mean())

3.5


In [25]:
print(arr.max())

6


In [26]:
print(arr.min())

1


In [2]:
a = np.array([2,4,6])
b = np.array([1,3,5])

NameError: name 'np' is not defined

In [32]:
print(a+b)

[ 3  7 11]


In [33]:
print(a*3)

[ 6 12 18]


In [1]:
print(a.mean())

NameError: name 'a' is not defined

In [1]:
import numpy as np