In [2]:
my_list = {1,2,3,4}

In [3]:
print(my_list)

{1, 2, 3, 4}


In [7]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [8]:
print(arr.ndim)

1


In [10]:
print(arr.shape)

(4,)


In [11]:
print(arr.dtype)

int64


In [14]:
arr + 5

array([6, 7, 8, 9])

In [15]:
arr * 2

array([2, 4, 6, 8])

In [18]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
print(a+b)

[11 22 33 44]


In [20]:
arr = np.array([10,20,30,40])
print(arr[0])
print(arr[-1])
print(arr[1:3])

10
40
[20 30]


In [21]:
matrix = np.array([
    [1,2,3,4],
    [4,5,6,7]
])
print(matrix)

[[1 2 3 4]
 [4 5 6 7]]


In [22]:
print(matrix[0,1])

2


In [23]:
arr = np.array([1,2,3,4,5,6])
print(arr.sum())

21


In [24]:
print(arr.mean())

3.5


In [25]:
print(arr.max())

6


In [26]:
print(arr.min())

1


In [2]:
a = np.array([2,4,6])
b = np.array([1,3,5])

NameError: name 'np' is not defined

In [32]:
print(a+b)

[ 3  7 11]


In [33]:
print(a*3)

[ 6 12 18]


In [1]:
print(a.mean())

NameError: name 'a' is not defined

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
print(arr + 10)

[11 12 13 14]


In [5]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])
print(matrix * 2)

[[ 2  4  6]
 [ 8 10 12]]


In [6]:
a = np.array([1,2,3])
b = np.array([10,20,30])
print(a+b)

[11 22 33]


In [8]:
a = np.array([[1],[2],[3]])
b = np.array([10,20,30])
print(a+b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [12]:
arr = np.array([10,20,30,40,50,60,70])
print(arr[arr > 25])

[30 40 50 60 70]


In [13]:
print(arr[(arr > 25) &  (arr < 50)])

[30 40]


In [14]:
arr[arr < 30 ] = 0
print(arr)

[ 0  0 30 40 50 60 70]


In [15]:
arr = np.array([5,10,15,20,25,30])

In [16]:
print(arr[arr > 15])

[20 25 30]


In [17]:
arr[arr < 20] = 0
print(arr)

[ 0  0  0 20 25 30]


In [18]:
print(arr + 5)

[ 5  5  5 25 30 35]


In [2]:
import numpy as np
np.random.rand(5)

array([0.99714317, 0.39476104, 0.48033302, 0.97388199, 0.99499354])

In [3]:
np.random.rand(3,4)

array([[0.23996214, 0.95122949, 0.30225652, 0.80855014],
       [0.677452  , 0.2063152 , 0.64754115, 0.08756928],
       [0.22376065, 0.77556557, 0.08310598, 0.67200696]])

In [4]:
np.random.randint(1,10, size=5)

array([5, 3, 3, 1, 4])

In [5]:
np.random.randn(5)

array([0.28088803, 1.45180935, 1.431341  , 2.60038244, 0.30844748])

In [6]:
np.random.seed(42)
np.random.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

In [7]:
arr = np.arange(6)
print(arr)

[0 1 2 3 4 5]


In [8]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
arr.reshape(3,-1)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [10]:
matrix = np.array([[1,2,3],[4,5,6]])
matrix.flatten()

array([1, 2, 3, 4, 5, 6])

In [11]:
arr = np.arange(12)
arr.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
arr = np.random.randint(1,5, size=(2,2))
print(arr)

[[1 1]
 [3 2]]


In [13]:
arr.flatten()

array([1, 1, 3, 2])

In [14]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [16]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [19]:
arr = np.array([1,2,3,4,5,6])
np.split(arr, 3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [22]:
matrix = np.array([[1,2],[3,4],[5,6]])

np.vsplit(matrix, 3)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

In [23]:
np.hsplit(matrix, 2)

[array([[1],
        [3],
        [5]]),
 array([[2],
        [4],
        [6]])]

In [25]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [26]:
np.linalg.det(a)

np.float64(-2.0000000000000004)

In [27]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [28]:
a = np.array([[2, 0],
              [1, 3]])

b = np.array([[1, 4],
              [2, 5]])


In [29]:
np.dot(a,b)

array([[ 2,  8],
       [ 7, 19]])

In [30]:
np.linalg.det(a)

np.float64(6.0)

In [32]:
np.stack((a))

array([[2, 0],
       [1, 3]])

In [33]:
np.vstack((b))

array([[1, 4],
       [2, 5]])